.TH cm-dir 1
.SH NAME
cm-dir \- configuration management for directories
.SH SYNOPSIS
.B cm-dir
.RB [ \-a ]
.RB [ \-g
.IR group ]
.RB [ \-m
.IR mode ]
.RB [ -n ]
.RB [ \-o
.IR owner ]
.RB [ \-r ]
.RB [ \-v ]
.I dir
.SH DESCRIPTION
cm-dir is a program for decalratively managing directory state and configuration.
.SH OPTIONS
.TP
.B \-a
ensure directory is absent
.TP
.B \-g group
ensure directory group is
.I group
.TP
.B \-h
display help message
.TP
.B \-m mode
ensure directory mode is
.I mode
.TP
.B \-n
noop run. Do not commit changes
.TP
.B \-o owner
ensure directory owner is
.I owner
.TP
.B \-r
apply configuration recursively
.TP
.B \-v
verbose output
.SH AUTHORS
Copyright \(co 2015 by Virgin Operators Society
