.TH cm-pkg 1
.SH NAME
cm-pkg \- configuration managment for packages
.SH SYNOPSIS
.B cm-pkg
.RB [ \-a ]
.RB [ \-n ]
.RB [ \-v ]
.I package
.SH DESCRIPTION
cm-pkg is a program for managing package state and configuration declaratively.
.SH OPTIONS
.TP
.B \-a
ensure package is absent
.TP
.B \-n
noop run. Do not commit changes
.TP
.B \-v
verbose output
.SH AUTHORS
Copyright \(co 2015 by Virgin Operators Society
